version: '3'
services:
  client:
    container_name: client
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER=http://localhost:5000
    command: yarn start
    stdin_open: true
    tty: true
  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://localhost:27017
      - CLIENT=http://localhost:3000
    command: yarn start
  db:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017